language: java
sudo: false
install:
  - (mvn license:check package || echo) > /dev/null # pre-run the script to install plugins
  - rm -r target # clean directory
script: mvn license:check package
jdk: [oraclejdk8]
